import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [text, setText] = useState("");
  const [tasks, setTask] = useState([
    { id: 1, text: "Learn typescript", done: false },
    { id: 2, text: "Learn Next.js", done: true },
  ]);

  const handleSubmit = (e) => {
    e.preventDefault();

    setTask([...tasks, { id: tasks.length + 1, text, done: false }]);

    setText("");
  };

  const handleCheck = (task) => {
    setTask(
      tasks.map((t) => (t.id === task.id ? { ...t, done: !task.done } : t))
    );
  };

  return (
    <div className="">
      <Head>
        <title>Testing React.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className="min-h-screen flex justify-center items-center">
        <div className="text-gray-300 p-10 border border-gray-300 w-1/4 rounded-md">
          <form onSubmit={handleSubmit}>
            <div className="flex">
              <input
                type="text"
                onChange={(e) => setText(e.target.value)}
                value={text}
                data-testid="input-task"
                className="form-input px-4 py-3 flex-1 bg-transparent text-gray-300"
                placeholder="Write your next goal here..."
              />
              <button
                data-testid="submit"
                className="px-8 py-2 bg-slate-300 text-sky-700"
              >
                Add goal
              </button>
            </div>
          </form>

          <div className="flex flex-col mt-4">
            {tasks.map((task, index) => (
              <div data-testid="item" key={task.text} className="my-2 text-xl">
                <input
                  type="checkbox"
                  className="form-checkbox h-6 w-6 rounded text-gray-400 mr-2"
                  checked={task.done}
                  onChange={() => handleCheck(task)}
                />
                {task.text}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
